version: 2.1.1.{build}
image: Visual Studio 2017

branches:
  only:
    - master
configuration:
  - Release
environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=9
  PROJECT: toofz.NecroDancer.LoadData
cache:
  - '%LocalAppData%\NuGet\Cache'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  
before_build:
  - nuget update -self
  - appveyor-retry nuget restore -Verbosity quiet
build:
  project: $(PROJECT).sln
  verbosity: minimal